// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwvqebgmzoncxfrnyodx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3dnFlYmdtem9uY3hmcm55b2R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5OTMyODgsImV4cCI6MjA1OTU2OTI4OH0.fLkylqbjqcm7TLicbEwULbheapkw-8d4vOrLs9mfSPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);